### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by bylengfeng** [zzyandzzy/xp-zhimiao#2]
需要编译嘛？微x模块在太极可用，能否用太极模块

**Comment by zzyandzzy** [comment]
目前需要编译, 后面我直接提供一个编译版, 微X模块能用, 这个模块也没问题.

**Comment by bylengfeng** [comment]
> 目前需要编译, 后面我直接提供一个编译版, 微X模块能用, 这个模块也没问题.

感谢大佬！！

**Comment by EdwardLee888** [comment]
能否出个教程感谢大佬

**Comment by zzyandzzy** [comment]
> > 目前需要编译, 后面我直接提供一个编译版, 微X模块能用, 这个模块也没问题.
> 
> 感谢大佬！！

已经发布了release
