### ISSUE TITLE
你好，咨询一下AES加密

### ISSUE THREAD

**Issue by relaxcn** [zzyandzzy/xp-zhimiao#4]
请问一下，我写了个小程序发现`Signature`会变化。而小程序使用前16未作为key。
我对于AES CBC加密也是刚接触。问一下这个`Signature`变化会影响解密吗？

**Comment by relaxcn** [comment]
我备用机是VIvo的，实在是太难Root了😂

**Comment by zzyandzzy** [comment]
> 请问一下，我写了个小程序发现`Signature`会变化。而小程序使用前16未作为key。 我对于AES CBC加密也是刚接触。问一下这个`Signature`变化会影响解密吗？

那肯定影响解密啊, `Signature`是微信小程序登录后用`加密算法本地生成`的, 这个模块也是hook了生成后的结果, 建议10分钟左右获取`Signature`以免失效.
