### ISSUE TITLE
约苗只是会抢购第一个预约日期吗？

### ISSUE THREAD

**Issue by relaxcn** [zzyandzzy/xp-zhimiao#7]
这里我随便找了一个测试

第一个18号已经没了，但是后面的日期还有。软件会显示`已经没苗了`
![image](https://user-images.githubusercontent.com/64476349/149930871-893c4f8b-1597-45b5-93ef-59baa791c6a0.png)

![image](https://user-images.githubusercontent.com/64476349/149931008-bda5d7f4-2498-4527-997d-a76c585a83d1.png)

![image](https://user-images.githubusercontent.com/64476349/149930719-d585b088-07ea-4481-b862-cbc472b0c0c4.png)

**Comment by relaxcn** [comment]
真实的场景肯定是第一个预约日期就够了的

**Comment by zzyandzzy** [comment]
> 真实的场景肯定是第一个预约日期就够了的

是的, 根据我的经验, 单IP你第一个或者其中一个抢不到, 其他的也抢不到.单个IP只有10或更少的QPS, 多了封号.

**Comment by EdwardLee888** [comment]
哥们你这是真机操作的还是模拟器

**Comment by relaxcn** [comment]
模拟器
