### ISSUE TITLE
请问抢购时间处该怎么填？

### ISSUE THREAD

**Issue by Rookie143** [zzyandzzy/xp-zhimiao#8]
是默认不用填就可以吗？默认不填的话是只抢第一天？希望作者可以在readme中给个示范的案例
我看提示说用“，”隔开，但我无法输入“，”
望大佬回复，谢谢！

**Comment by zzyandzzy** [comment]
这里的抢购时间实际上是接种时间, 格式: **2021-11-11**, 基本上填一个就行, 一个抢不到其他的也抢不到.

**Comment by Rookie143** [comment]
> 这里的抢购时间实际上是接种时间, 格式: **2021-11-11**, 基本上填一个就行, 一个抢不到其他的也抢不到.

但是我需要如何知道接种时间呢？刚刚开抢后等我进去查看到时间已经显示抢完了，太惨了

**Comment by zzyandzzy** [comment]
> > 这里的抢购时间实际上是接种时间, 格式: **2021-11-11**, 基本上填一个就行, 一个抢不到其他的也抢不到.
> 
> 
> 
> 但是我需要如何知道接种时间呢？刚刚开抢后等我进去查看到时间已经显示抢完了，太惨了

这个就要靠自己收集信息了，不填的话会默认多发一个请求去获取接种时间，就更慢了。
